### ISSUE TITLE
Just saying

### ISSUE THREAD

**Issue by neilyoung** [homettp/homettp#1]
...I really like your work. To marry Vue, Inertia and Go - awesome. Also your code samples are very instructive.

Came from Laravel, found Goravel, added your library to a Goravel instance and used vite for the frontend requirements - just to find out down the road, that Goravel in the end is just (to stay in the PHP namespace) more a "facade"... Cannot really compete with Laravel, especially not w.r.t the database easyness (ORM, migration, etc).

Your work is pretty awesome and clean and it would be great if it would have ORM support too. But I'll keep it in my mind as a good starter (not that bloated) for GO/Vue/Inertia projects

**Comment by petaki** [comment]
Thank you!
